//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 02:20:29 PM MST 
//


package org.xenbase.literature.jaxb.beans.pubmed;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mmlMath"
})
@XmlRootElement(name = "DispFormula")
public class DispFormula {

    @XmlElement(name = "mml:math", required = true)
    protected MmlMath mmlMath;

    /**
     * Gets the value of the mmlMath property.
     * 
     * @return
     *     possible object is
     *     {@link MmlMath }
     *     
     */
    public MmlMath getMmlMath() {
        return mmlMath;
    }

    /**
     * Sets the value of the mmlMath property.
     * 
     * @param value
     *     allowed object is
     *     {@link MmlMath }
     *     
     */
    public void setMmlMath(MmlMath value) {
        this.mmlMath = value;
    }

}
