//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.12.20 at 02:20:29 PM MST 
//


package org.xenbase.literature.jaxb.beans.pubmed;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.xenbase.literature.jaxb.beans.pubmed package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.xenbase.literature.jaxb.beans.pubmed
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MedlinePgn }
     * 
     */
    public MedlinePgn createMedlinePgn() {
        return new MedlinePgn();
    }

    /**
     * Create an instance of {@link MmlFn }
     * 
     */
    public MmlFn createMmlFn() {
        return new MmlFn();
    }

    /**
     * Create an instance of {@link MmlPiecewise }
     * 
     */
    public MmlPiecewise createMmlPiecewise() {
        return new MmlPiecewise();
    }

    /**
     * Create an instance of {@link MmlReln }
     * 
     */
    public MmlReln createMmlReln() {
        return new MmlReln();
    }

    /**
     * Create an instance of {@link MmlDeclare }
     * 
     */
    public MmlDeclare createMmlDeclare() {
        return new MmlDeclare();
    }

    /**
     * Create an instance of {@link MmlInterval }
     * 
     */
    public MmlInterval createMmlInterval() {
        return new MmlInterval();
    }

    /**
     * Create an instance of {@link MmlInverse }
     * 
     */
    public MmlInverse createMmlInverse() {
        return new MmlInverse();
    }

    /**
     * Create an instance of {@link MmlIdent }
     * 
     */
    public MmlIdent createMmlIdent() {
        return new MmlIdent();
    }

    /**
     * Create an instance of {@link MmlDomain }
     * 
     */
    public MmlDomain createMmlDomain() {
        return new MmlDomain();
    }

    /**
     * Create an instance of {@link MmlCodomain }
     * 
     */
    public MmlCodomain createMmlCodomain() {
        return new MmlCodomain();
    }

    /**
     * Create an instance of {@link MmlImage }
     * 
     */
    public MmlImage createMmlImage() {
        return new MmlImage();
    }

    /**
     * Create an instance of {@link MmlLn }
     * 
     */
    public MmlLn createMmlLn() {
        return new MmlLn();
    }

    /**
     * Create an instance of {@link MmlLog }
     * 
     */
    public MmlLog createMmlLog() {
        return new MmlLog();
    }

    /**
     * Create an instance of {@link MmlMoment }
     * 
     */
    public MmlMoment createMmlMoment() {
        return new MmlMoment();
    }

    /**
     * Create an instance of {@link MmlLambda }
     * 
     */
    public MmlLambda createMmlLambda() {
        return new MmlLambda();
    }

    /**
     * Create an instance of {@link MmlCompose }
     * 
     */
    public MmlCompose createMmlCompose() {
        return new MmlCompose();
    }

    /**
     * Create an instance of {@link MmlQuotient }
     * 
     */
    public MmlQuotient createMmlQuotient() {
        return new MmlQuotient();
    }

    /**
     * Create an instance of {@link MmlDivide }
     * 
     */
    public MmlDivide createMmlDivide() {
        return new MmlDivide();
    }

    /**
     * Create an instance of {@link MmlMinus }
     * 
     */
    public MmlMinus createMmlMinus() {
        return new MmlMinus();
    }

    /**
     * Create an instance of {@link MmlPower }
     * 
     */
    public MmlPower createMmlPower() {
        return new MmlPower();
    }

    /**
     * Create an instance of {@link MmlRem }
     * 
     */
    public MmlRem createMmlRem() {
        return new MmlRem();
    }

    /**
     * Create an instance of {@link MmlRoot }
     * 
     */
    public MmlRoot createMmlRoot() {
        return new MmlRoot();
    }

    /**
     * Create an instance of {@link MmlFactorial }
     * 
     */
    public MmlFactorial createMmlFactorial() {
        return new MmlFactorial();
    }

    /**
     * Create an instance of {@link MmlAbs }
     * 
     */
    public MmlAbs createMmlAbs() {
        return new MmlAbs();
    }

    /**
     * Create an instance of {@link MmlConjugate }
     * 
     */
    public MmlConjugate createMmlConjugate() {
        return new MmlConjugate();
    }

    /**
     * Create an instance of {@link MmlArg }
     * 
     */
    public MmlArg createMmlArg() {
        return new MmlArg();
    }

    /**
     * Create an instance of {@link MmlReal }
     * 
     */
    public MmlReal createMmlReal() {
        return new MmlReal();
    }

    /**
     * Create an instance of {@link MmlImaginary }
     * 
     */
    public MmlImaginary createMmlImaginary() {
        return new MmlImaginary();
    }

    /**
     * Create an instance of {@link MmlFloor }
     * 
     */
    public MmlFloor createMmlFloor() {
        return new MmlFloor();
    }

    /**
     * Create an instance of {@link MmlCeiling }
     * 
     */
    public MmlCeiling createMmlCeiling() {
        return new MmlCeiling();
    }

    /**
     * Create an instance of {@link MmlExp }
     * 
     */
    public MmlExp createMmlExp() {
        return new MmlExp();
    }

    /**
     * Create an instance of {@link MmlMax }
     * 
     */
    public MmlMax createMmlMax() {
        return new MmlMax();
    }

    /**
     * Create an instance of {@link MmlMin }
     * 
     */
    public MmlMin createMmlMin() {
        return new MmlMin();
    }

    /**
     * Create an instance of {@link MmlPlus }
     * 
     */
    public MmlPlus createMmlPlus() {
        return new MmlPlus();
    }

    /**
     * Create an instance of {@link MmlTimes }
     * 
     */
    public MmlTimes createMmlTimes() {
        return new MmlTimes();
    }

    /**
     * Create an instance of {@link MmlGcd }
     * 
     */
    public MmlGcd createMmlGcd() {
        return new MmlGcd();
    }

    /**
     * Create an instance of {@link MmlLcm }
     * 
     */
    public MmlLcm createMmlLcm() {
        return new MmlLcm();
    }

    /**
     * Create an instance of {@link MmlAnd }
     * 
     */
    public MmlAnd createMmlAnd() {
        return new MmlAnd();
    }

    /**
     * Create an instance of {@link MmlOr }
     * 
     */
    public MmlOr createMmlOr() {
        return new MmlOr();
    }

    /**
     * Create an instance of {@link MmlXor }
     * 
     */
    public MmlXor createMmlXor() {
        return new MmlXor();
    }

    /**
     * Create an instance of {@link MmlNot }
     * 
     */
    public MmlNot createMmlNot() {
        return new MmlNot();
    }

    /**
     * Create an instance of {@link MmlImplies }
     * 
     */
    public MmlImplies createMmlImplies() {
        return new MmlImplies();
    }

    /**
     * Create an instance of {@link MmlEquivalent }
     * 
     */
    public MmlEquivalent createMmlEquivalent() {
        return new MmlEquivalent();
    }

    /**
     * Create an instance of {@link MmlForall }
     * 
     */
    public MmlForall createMmlForall() {
        return new MmlForall();
    }

    /**
     * Create an instance of {@link MmlExists }
     * 
     */
    public MmlExists createMmlExists() {
        return new MmlExists();
    }

    /**
     * Create an instance of {@link MmlEq }
     * 
     */
    public MmlEq createMmlEq() {
        return new MmlEq();
    }

    /**
     * Create an instance of {@link MmlGt }
     * 
     */
    public MmlGt createMmlGt() {
        return new MmlGt();
    }

    /**
     * Create an instance of {@link MmlLt }
     * 
     */
    public MmlLt createMmlLt() {
        return new MmlLt();
    }

    /**
     * Create an instance of {@link MmlGeq }
     * 
     */
    public MmlGeq createMmlGeq() {
        return new MmlGeq();
    }

    /**
     * Create an instance of {@link MmlLeq }
     * 
     */
    public MmlLeq createMmlLeq() {
        return new MmlLeq();
    }

    /**
     * Create an instance of {@link MmlNeq }
     * 
     */
    public MmlNeq createMmlNeq() {
        return new MmlNeq();
    }

    /**
     * Create an instance of {@link MmlApprox }
     * 
     */
    public MmlApprox createMmlApprox() {
        return new MmlApprox();
    }

    /**
     * Create an instance of {@link MmlFactorof }
     * 
     */
    public MmlFactorof createMmlFactorof() {
        return new MmlFactorof();
    }

    /**
     * Create an instance of {@link MmlTendsto }
     * 
     */
    public MmlTendsto createMmlTendsto() {
        return new MmlTendsto();
    }

    /**
     * Create an instance of {@link MmlInt }
     * 
     */
    public MmlInt createMmlInt() {
        return new MmlInt();
    }

    /**
     * Create an instance of {@link MmlDiff }
     * 
     */
    public MmlDiff createMmlDiff() {
        return new MmlDiff();
    }

    /**
     * Create an instance of {@link MmlPartialdiff }
     * 
     */
    public MmlPartialdiff createMmlPartialdiff() {
        return new MmlPartialdiff();
    }

    /**
     * Create an instance of {@link MmlDivergence }
     * 
     */
    public MmlDivergence createMmlDivergence() {
        return new MmlDivergence();
    }

    /**
     * Create an instance of {@link MmlGrad }
     * 
     */
    public MmlGrad createMmlGrad() {
        return new MmlGrad();
    }

    /**
     * Create an instance of {@link MmlCurl }
     * 
     */
    public MmlCurl createMmlCurl() {
        return new MmlCurl();
    }

    /**
     * Create an instance of {@link MmlLaplacian }
     * 
     */
    public MmlLaplacian createMmlLaplacian() {
        return new MmlLaplacian();
    }

    /**
     * Create an instance of {@link MmlSet }
     * 
     */
    public MmlSet createMmlSet() {
        return new MmlSet();
    }

    /**
     * Create an instance of {@link MmlList }
     * 
     */
    public MmlList createMmlList() {
        return new MmlList();
    }

    /**
     * Create an instance of {@link MmlUnion }
     * 
     */
    public MmlUnion createMmlUnion() {
        return new MmlUnion();
    }

    /**
     * Create an instance of {@link MmlIntersect }
     * 
     */
    public MmlIntersect createMmlIntersect() {
        return new MmlIntersect();
    }

    /**
     * Create an instance of {@link MmlCartesianproduct }
     * 
     */
    public MmlCartesianproduct createMmlCartesianproduct() {
        return new MmlCartesianproduct();
    }

    /**
     * Create an instance of {@link MmlIn }
     * 
     */
    public MmlIn createMmlIn() {
        return new MmlIn();
    }

    /**
     * Create an instance of {@link MmlNotin }
     * 
     */
    public MmlNotin createMmlNotin() {
        return new MmlNotin();
    }

    /**
     * Create an instance of {@link MmlNotsubset }
     * 
     */
    public MmlNotsubset createMmlNotsubset() {
        return new MmlNotsubset();
    }

    /**
     * Create an instance of {@link MmlNotprsubset }
     * 
     */
    public MmlNotprsubset createMmlNotprsubset() {
        return new MmlNotprsubset();
    }

    /**
     * Create an instance of {@link MmlSetdiff }
     * 
     */
    public MmlSetdiff createMmlSetdiff() {
        return new MmlSetdiff();
    }

    /**
     * Create an instance of {@link MmlSubset }
     * 
     */
    public MmlSubset createMmlSubset() {
        return new MmlSubset();
    }

    /**
     * Create an instance of {@link MmlPrsubset }
     * 
     */
    public MmlPrsubset createMmlPrsubset() {
        return new MmlPrsubset();
    }

    /**
     * Create an instance of {@link MmlCard }
     * 
     */
    public MmlCard createMmlCard() {
        return new MmlCard();
    }

    /**
     * Create an instance of {@link MmlSum }
     * 
     */
    public MmlSum createMmlSum() {
        return new MmlSum();
    }

    /**
     * Create an instance of {@link MmlProduct }
     * 
     */
    public MmlProduct createMmlProduct() {
        return new MmlProduct();
    }

    /**
     * Create an instance of {@link MmlLimit }
     * 
     */
    public MmlLimit createMmlLimit() {
        return new MmlLimit();
    }

    /**
     * Create an instance of {@link MmlSin }
     * 
     */
    public MmlSin createMmlSin() {
        return new MmlSin();
    }

    /**
     * Create an instance of {@link MmlCos }
     * 
     */
    public MmlCos createMmlCos() {
        return new MmlCos();
    }

    /**
     * Create an instance of {@link MmlTan }
     * 
     */
    public MmlTan createMmlTan() {
        return new MmlTan();
    }

    /**
     * Create an instance of {@link MmlSec }
     * 
     */
    public MmlSec createMmlSec() {
        return new MmlSec();
    }

    /**
     * Create an instance of {@link MmlCsc }
     * 
     */
    public MmlCsc createMmlCsc() {
        return new MmlCsc();
    }

    /**
     * Create an instance of {@link MmlCot }
     * 
     */
    public MmlCot createMmlCot() {
        return new MmlCot();
    }

    /**
     * Create an instance of {@link MmlSinh }
     * 
     */
    public MmlSinh createMmlSinh() {
        return new MmlSinh();
    }

    /**
     * Create an instance of {@link MmlCosh }
     * 
     */
    public MmlCosh createMmlCosh() {
        return new MmlCosh();
    }

    /**
     * Create an instance of {@link MmlTanh }
     * 
     */
    public MmlTanh createMmlTanh() {
        return new MmlTanh();
    }

    /**
     * Create an instance of {@link MmlSech }
     * 
     */
    public MmlSech createMmlSech() {
        return new MmlSech();
    }

    /**
     * Create an instance of {@link MmlCsch }
     * 
     */
    public MmlCsch createMmlCsch() {
        return new MmlCsch();
    }

    /**
     * Create an instance of {@link MmlCoth }
     * 
     */
    public MmlCoth createMmlCoth() {
        return new MmlCoth();
    }

    /**
     * Create an instance of {@link MmlArcsin }
     * 
     */
    public MmlArcsin createMmlArcsin() {
        return new MmlArcsin();
    }

    /**
     * Create an instance of {@link MmlArccos }
     * 
     */
    public MmlArccos createMmlArccos() {
        return new MmlArccos();
    }

    /**
     * Create an instance of {@link MmlArctan }
     * 
     */
    public MmlArctan createMmlArctan() {
        return new MmlArctan();
    }

    /**
     * Create an instance of {@link MmlArccosh }
     * 
     */
    public MmlArccosh createMmlArccosh() {
        return new MmlArccosh();
    }

    /**
     * Create an instance of {@link MmlArccot }
     * 
     */
    public MmlArccot createMmlArccot() {
        return new MmlArccot();
    }

    /**
     * Create an instance of {@link MmlArccoth }
     * 
     */
    public MmlArccoth createMmlArccoth() {
        return new MmlArccoth();
    }

    /**
     * Create an instance of {@link MmlArccsc }
     * 
     */
    public MmlArccsc createMmlArccsc() {
        return new MmlArccsc();
    }

    /**
     * Create an instance of {@link MmlArccsch }
     * 
     */
    public MmlArccsch createMmlArccsch() {
        return new MmlArccsch();
    }

    /**
     * Create an instance of {@link MmlArcsec }
     * 
     */
    public MmlArcsec createMmlArcsec() {
        return new MmlArcsec();
    }

    /**
     * Create an instance of {@link MmlArcsech }
     * 
     */
    public MmlArcsech createMmlArcsech() {
        return new MmlArcsech();
    }

    /**
     * Create an instance of {@link MmlArcsinh }
     * 
     */
    public MmlArcsinh createMmlArcsinh() {
        return new MmlArcsinh();
    }

    /**
     * Create an instance of {@link MmlArctanh }
     * 
     */
    public MmlArctanh createMmlArctanh() {
        return new MmlArctanh();
    }

    /**
     * Create an instance of {@link MmlMean }
     * 
     */
    public MmlMean createMmlMean() {
        return new MmlMean();
    }

    /**
     * Create an instance of {@link MmlSdev }
     * 
     */
    public MmlSdev createMmlSdev() {
        return new MmlSdev();
    }

    /**
     * Create an instance of {@link MmlVariance }
     * 
     */
    public MmlVariance createMmlVariance() {
        return new MmlVariance();
    }

    /**
     * Create an instance of {@link MmlMedian }
     * 
     */
    public MmlMedian createMmlMedian() {
        return new MmlMedian();
    }

    /**
     * Create an instance of {@link MmlMode }
     * 
     */
    public MmlMode createMmlMode() {
        return new MmlMode();
    }

    /**
     * Create an instance of {@link MmlVector }
     * 
     */
    public MmlVector createMmlVector() {
        return new MmlVector();
    }

    /**
     * Create an instance of {@link MmlMatrix }
     * 
     */
    public MmlMatrix createMmlMatrix() {
        return new MmlMatrix();
    }

    /**
     * Create an instance of {@link MmlMatrixrow }
     * 
     */
    public MmlMatrixrow createMmlMatrixrow() {
        return new MmlMatrixrow();
    }

    /**
     * Create an instance of {@link MmlDeterminant }
     * 
     */
    public MmlDeterminant createMmlDeterminant() {
        return new MmlDeterminant();
    }

    /**
     * Create an instance of {@link MmlTranspose }
     * 
     */
    public MmlTranspose createMmlTranspose() {
        return new MmlTranspose();
    }

    /**
     * Create an instance of {@link MmlSelector }
     * 
     */
    public MmlSelector createMmlSelector() {
        return new MmlSelector();
    }

    /**
     * Create an instance of {@link MmlVectorproduct }
     * 
     */
    public MmlVectorproduct createMmlVectorproduct() {
        return new MmlVectorproduct();
    }

    /**
     * Create an instance of {@link MmlScalarproduct }
     * 
     */
    public MmlScalarproduct createMmlScalarproduct() {
        return new MmlScalarproduct();
    }

    /**
     * Create an instance of {@link MmlOuterproduct }
     * 
     */
    public MmlOuterproduct createMmlOuterproduct() {
        return new MmlOuterproduct();
    }

    /**
     * Create an instance of {@link MmlIntegers }
     * 
     */
    public MmlIntegers createMmlIntegers() {
        return new MmlIntegers();
    }

    /**
     * Create an instance of {@link MmlReals }
     * 
     */
    public MmlReals createMmlReals() {
        return new MmlReals();
    }

    /**
     * Create an instance of {@link MmlRationals }
     * 
     */
    public MmlRationals createMmlRationals() {
        return new MmlRationals();
    }

    /**
     * Create an instance of {@link MmlNaturalnumbers }
     * 
     */
    public MmlNaturalnumbers createMmlNaturalnumbers() {
        return new MmlNaturalnumbers();
    }

    /**
     * Create an instance of {@link MmlComplexes }
     * 
     */
    public MmlComplexes createMmlComplexes() {
        return new MmlComplexes();
    }

    /**
     * Create an instance of {@link MmlPrimes }
     * 
     */
    public MmlPrimes createMmlPrimes() {
        return new MmlPrimes();
    }

    /**
     * Create an instance of {@link MmlEmptyset }
     * 
     */
    public MmlEmptyset createMmlEmptyset() {
        return new MmlEmptyset();
    }

    /**
     * Create an instance of {@link MmlExponentiale }
     * 
     */
    public MmlExponentiale createMmlExponentiale() {
        return new MmlExponentiale();
    }

    /**
     * Create an instance of {@link MmlImaginaryi }
     * 
     */
    public MmlImaginaryi createMmlImaginaryi() {
        return new MmlImaginaryi();
    }

    /**
     * Create an instance of {@link MmlNotanumber }
     * 
     */
    public MmlNotanumber createMmlNotanumber() {
        return new MmlNotanumber();
    }

    /**
     * Create an instance of {@link MmlTrue }
     * 
     */
    public MmlTrue createMmlTrue() {
        return new MmlTrue();
    }

    /**
     * Create an instance of {@link MmlFalse }
     * 
     */
    public MmlFalse createMmlFalse() {
        return new MmlFalse();
    }

    /**
     * Create an instance of {@link MmlPi }
     * 
     */
    public MmlPi createMmlPi() {
        return new MmlPi();
    }

    /**
     * Create an instance of {@link MmlEulergamma }
     * 
     */
    public MmlEulergamma createMmlEulergamma() {
        return new MmlEulergamma();
    }

    /**
     * Create an instance of {@link MmlInfinity }
     * 
     */
    public MmlInfinity createMmlInfinity() {
        return new MmlInfinity();
    }

    /**
     * Create an instance of {@link MmlSemantics }
     * 
     */
    public MmlSemantics createMmlSemantics() {
        return new MmlSemantics();
    }

    /**
     * Create an instance of {@link MmlCn }
     * 
     */
    public MmlCn createMmlCn() {
        return new MmlCn();
    }

    /**
     * Create an instance of {@link MmlCi }
     * 
     */
    public MmlCi createMmlCi() {
        return new MmlCi();
    }

    /**
     * Create an instance of {@link MmlCsymbol }
     * 
     */
    public MmlCsymbol createMmlCsymbol() {
        return new MmlCsymbol();
    }

    /**
     * Create an instance of {@link MmlApply }
     * 
     */
    public MmlApply createMmlApply() {
        return new MmlApply();
    }

    /**
     * Create an instance of {@link MmlBind }
     * 
     */
    public MmlBind createMmlBind() {
        return new MmlBind();
    }

    /**
     * Create an instance of {@link MmlShare }
     * 
     */
    public MmlShare createMmlShare() {
        return new MmlShare();
    }

    /**
     * Create an instance of {@link MmlCerror }
     * 
     */
    public MmlCerror createMmlCerror() {
        return new MmlCerror();
    }

    /**
     * Create an instance of {@link MmlCbytes }
     * 
     */
    public MmlCbytes createMmlCbytes() {
        return new MmlCbytes();
    }

    /**
     * Create an instance of {@link MmlCs }
     * 
     */
    public MmlCs createMmlCs() {
        return new MmlCs();
    }

    /**
     * Create an instance of {@link GeneSymbolList }
     * 
     */
    public GeneSymbolList createGeneSymbolList() {
        return new GeneSymbolList();
    }

    /**
     * Create an instance of {@link GeneSymbol }
     * 
     */
    public GeneSymbol createGeneSymbol() {
        return new GeneSymbol();
    }

    /**
     * Create an instance of {@link History }
     * 
     */
    public History createHistory() {
        return new History();
    }

    /**
     * Create an instance of {@link PubMedPubDate }
     * 
     */
    public PubMedPubDate createPubMedPubDate() {
        return new PubMedPubDate();
    }

    /**
     * Create an instance of {@link NameOfSubstance }
     * 
     */
    public NameOfSubstance createNameOfSubstance() {
        return new NameOfSubstance();
    }

    /**
     * Create an instance of {@link Month }
     * 
     */
    public Month createMonth() {
        return new Month();
    }

    /**
     * Create an instance of {@link PubmedBookArticle }
     * 
     */
    public PubmedBookArticle createPubmedBookArticle() {
        return new PubmedBookArticle();
    }

    /**
     * Create an instance of {@link BookDocument }
     * 
     */
    public BookDocument createBookDocument() {
        return new BookDocument();
    }

    /**
     * Create an instance of {@link PubmedBookData }
     * 
     */
    public PubmedBookData createPubmedBookData() {
        return new PubmedBookData();
    }

    /**
     * Create an instance of {@link Sections }
     * 
     */
    public Sections createSections() {
        return new Sections();
    }

    /**
     * Create an instance of {@link Section }
     * 
     */
    public Section createSection() {
        return new Section();
    }

    /**
     * Create an instance of {@link MmlMsrow }
     * 
     */
    public MmlMsrow createMmlMsrow() {
        return new MmlMsrow();
    }

    /**
     * Create an instance of {@link MmlMi }
     * 
     */
    public MmlMi createMmlMi() {
        return new MmlMi();
    }

    /**
     * Create an instance of {@link MmlMn }
     * 
     */
    public MmlMn createMmlMn() {
        return new MmlMn();
    }

    /**
     * Create an instance of {@link MmlMo }
     * 
     */
    public MmlMo createMmlMo() {
        return new MmlMo();
    }

    /**
     * Create an instance of {@link MmlMtext }
     * 
     */
    public MmlMtext createMmlMtext() {
        return new MmlMtext();
    }

    /**
     * Create an instance of {@link MmlMspace }
     * 
     */
    public MmlMspace createMmlMspace() {
        return new MmlMspace();
    }

    /**
     * Create an instance of {@link MmlMs }
     * 
     */
    public MmlMs createMmlMs() {
        return new MmlMs();
    }

    /**
     * Create an instance of {@link MmlMaligngroup }
     * 
     */
    public MmlMaligngroup createMmlMaligngroup() {
        return new MmlMaligngroup();
    }

    /**
     * Create an instance of {@link MmlMalignmark }
     * 
     */
    public MmlMalignmark createMmlMalignmark() {
        return new MmlMalignmark();
    }

    /**
     * Create an instance of {@link MmlMrow }
     * 
     */
    public MmlMrow createMmlMrow() {
        return new MmlMrow();
    }

    /**
     * Create an instance of {@link MmlMfrac }
     * 
     */
    public MmlMfrac createMmlMfrac() {
        return new MmlMfrac();
    }

    /**
     * Create an instance of {@link MmlMsqrt }
     * 
     */
    public MmlMsqrt createMmlMsqrt() {
        return new MmlMsqrt();
    }

    /**
     * Create an instance of {@link MmlMroot }
     * 
     */
    public MmlMroot createMmlMroot() {
        return new MmlMroot();
    }

    /**
     * Create an instance of {@link MmlMstyle }
     * 
     */
    public MmlMstyle createMmlMstyle() {
        return new MmlMstyle();
    }

    /**
     * Create an instance of {@link MmlMerror }
     * 
     */
    public MmlMerror createMmlMerror() {
        return new MmlMerror();
    }

    /**
     * Create an instance of {@link MmlMpadded }
     * 
     */
    public MmlMpadded createMmlMpadded() {
        return new MmlMpadded();
    }

    /**
     * Create an instance of {@link MmlMphantom }
     * 
     */
    public MmlMphantom createMmlMphantom() {
        return new MmlMphantom();
    }

    /**
     * Create an instance of {@link MmlMfenced }
     * 
     */
    public MmlMfenced createMmlMfenced() {
        return new MmlMfenced();
    }

    /**
     * Create an instance of {@link MmlMenclose }
     * 
     */
    public MmlMenclose createMmlMenclose() {
        return new MmlMenclose();
    }

    /**
     * Create an instance of {@link MmlMsub }
     * 
     */
    public MmlMsub createMmlMsub() {
        return new MmlMsub();
    }

    /**
     * Create an instance of {@link MmlMsup }
     * 
     */
    public MmlMsup createMmlMsup() {
        return new MmlMsup();
    }

    /**
     * Create an instance of {@link MmlMsubsup }
     * 
     */
    public MmlMsubsup createMmlMsubsup() {
        return new MmlMsubsup();
    }

    /**
     * Create an instance of {@link MmlMunder }
     * 
     */
    public MmlMunder createMmlMunder() {
        return new MmlMunder();
    }

    /**
     * Create an instance of {@link MmlMover }
     * 
     */
    public MmlMover createMmlMover() {
        return new MmlMover();
    }

    /**
     * Create an instance of {@link MmlMunderover }
     * 
     */
    public MmlMunderover createMmlMunderover() {
        return new MmlMunderover();
    }

    /**
     * Create an instance of {@link MmlMmultiscripts }
     * 
     */
    public MmlMmultiscripts createMmlMmultiscripts() {
        return new MmlMmultiscripts();
    }

    /**
     * Create an instance of {@link MmlMtable }
     * 
     */
    public MmlMtable createMmlMtable() {
        return new MmlMtable();
    }

    /**
     * Create an instance of {@link MmlMstack }
     * 
     */
    public MmlMstack createMmlMstack() {
        return new MmlMstack();
    }

    /**
     * Create an instance of {@link MmlMlongdiv }
     * 
     */
    public MmlMlongdiv createMmlMlongdiv() {
        return new MmlMlongdiv();
    }

    /**
     * Create an instance of {@link MmlMaction }
     * 
     */
    public MmlMaction createMmlMaction() {
        return new MmlMaction();
    }

    /**
     * Create an instance of {@link MmlNone }
     * 
     */
    public MmlNone createMmlNone() {
        return new MmlNone();
    }

    /**
     * Create an instance of {@link MmlBvar }
     * 
     */
    public MmlBvar createMmlBvar() {
        return new MmlBvar();
    }

    /**
     * Create an instance of {@link MmlDomainofapplication }
     * 
     */
    public MmlDomainofapplication createMmlDomainofapplication() {
        return new MmlDomainofapplication();
    }

    /**
     * Create an instance of {@link MmlCondition }
     * 
     */
    public MmlCondition createMmlCondition() {
        return new MmlCondition();
    }

    /**
     * Create an instance of {@link MmlLowlimit }
     * 
     */
    public MmlLowlimit createMmlLowlimit() {
        return new MmlLowlimit();
    }

    /**
     * Create an instance of {@link MmlUplimit }
     * 
     */
    public MmlUplimit createMmlUplimit() {
        return new MmlUplimit();
    }

    /**
     * Create an instance of {@link PubmedArticleSet }
     * 
     */
    public PubmedArticleSet createPubmedArticleSet() {
        return new PubmedArticleSet();
    }

    /**
     * Create an instance of {@link PubmedArticle }
     * 
     */
    public PubmedArticle createPubmedArticle() {
        return new PubmedArticle();
    }

    /**
     * Create an instance of {@link DeleteCitation }
     * 
     */
    public DeleteCitation createDeleteCitation() {
        return new DeleteCitation();
    }

    /**
     * Create an instance of {@link MmlMglyph }
     * 
     */
    public MmlMglyph createMmlMglyph() {
        return new MmlMglyph();
    }

    /**
     * Create an instance of {@link ForeName }
     * 
     */
    public ForeName createForeName() {
        return new ForeName();
    }

    /**
     * Create an instance of {@link MmlMomentabout }
     * 
     */
    public MmlMomentabout createMmlMomentabout() {
        return new MmlMomentabout();
    }

    /**
     * Create an instance of {@link AbstractText }
     * 
     */
    public AbstractText createAbstractText() {
        return new AbstractText();
    }

    /**
     * Create an instance of {@link CommentsCorrectionsList }
     * 
     */
    public CommentsCorrectionsList createCommentsCorrectionsList() {
        return new CommentsCorrectionsList();
    }

    /**
     * Create an instance of {@link CommentsCorrections }
     * 
     */
    public CommentsCorrections createCommentsCorrections() {
        return new CommentsCorrections();
    }

    /**
     * Create an instance of {@link Initials }
     * 
     */
    public Initials createInitials() {
        return new Initials();
    }

    /**
     * Create an instance of {@link Chemical }
     * 
     */
    public Chemical createChemical() {
        return new Chemical();
    }

    /**
     * Create an instance of {@link PMID }
     * 
     */
    public PMID createPMID() {
        return new PMID();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link Suffix }
     * 
     */
    public Suffix createSuffix() {
        return new Suffix();
    }

    /**
     * Create an instance of {@link CollectiveName }
     * 
     */
    public CollectiveName createCollectiveName() {
        return new CollectiveName();
    }

    /**
     * Create an instance of {@link Identifier }
     * 
     */
    public Identifier createIdentifier() {
        return new Identifier();
    }

    /**
     * Create an instance of {@link AffiliationInfo }
     * 
     */
    public AffiliationInfo createAffiliationInfo() {
        return new AffiliationInfo();
    }

    /**
     * Create an instance of {@link AccessionNumber }
     * 
     */
    public AccessionNumber createAccessionNumber() {
        return new AccessionNumber();
    }

    /**
     * Create an instance of {@link MedlineDate }
     * 
     */
    public MedlineDate createMedlineDate() {
        return new MedlineDate();
    }

    /**
     * Create an instance of {@link AccessionNumberList }
     * 
     */
    public AccessionNumberList createAccessionNumberList() {
        return new AccessionNumberList();
    }

    /**
     * Create an instance of {@link Sub }
     * 
     */
    public Sub createSub() {
        return new Sub();
    }

    /**
     * Create an instance of {@link Sup }
     * 
     */
    public Sup createSup() {
        return new Sup();
    }

    /**
     * Create an instance of {@link ArticleId }
     * 
     */
    public ArticleId createArticleId() {
        return new ArticleId();
    }

    /**
     * Create an instance of {@link Season }
     * 
     */
    public Season createSeason() {
        return new Season();
    }

    /**
     * Create an instance of {@link MedlineCitation }
     * 
     */
    public MedlineCitation createMedlineCitation() {
        return new MedlineCitation();
    }

    /**
     * Create an instance of {@link PubmedData }
     * 
     */
    public PubmedData createPubmedData() {
        return new PubmedData();
    }

    /**
     * Create an instance of {@link MmlMscarries }
     * 
     */
    public MmlMscarries createMmlMscarries() {
        return new MmlMscarries();
    }

    /**
     * Create an instance of {@link MmlMsline }
     * 
     */
    public MmlMsline createMmlMsline() {
        return new MmlMsline();
    }

    /**
     * Create an instance of {@link MmlMsgroup }
     * 
     */
    public MmlMsgroup createMmlMsgroup() {
        return new MmlMsgroup();
    }

    /**
     * Create an instance of {@link MmlMath }
     * 
     */
    public MmlMath createMmlMath() {
        return new MmlMath();
    }

    /**
     * Create an instance of {@link PersonalNameSubjectList }
     * 
     */
    public PersonalNameSubjectList createPersonalNameSubjectList() {
        return new PersonalNameSubjectList();
    }

    /**
     * Create an instance of {@link PersonalNameSubject }
     * 
     */
    public PersonalNameSubject createPersonalNameSubject() {
        return new PersonalNameSubject();
    }

    /**
     * Create an instance of {@link B }
     * 
     */
    public B createB() {
        return new B();
    }

    /**
     * Create an instance of {@link I }
     * 
     */
    public I createI() {
        return new I();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link ArticleIdList }
     * 
     */
    public ArticleIdList createArticleIdList() {
        return new ArticleIdList();
    }

    /**
     * Create an instance of {@link LocationLabel }
     * 
     */
    public LocationLabel createLocationLabel() {
        return new LocationLabel();
    }

    /**
     * Create an instance of {@link SectionTitle }
     * 
     */
    public SectionTitle createSectionTitle() {
        return new SectionTitle();
    }

    /**
     * Create an instance of {@link QualifierName }
     * 
     */
    public QualifierName createQualifierName() {
        return new QualifierName();
    }

    /**
     * Create an instance of {@link Year }
     * 
     */
    public Year createYear() {
        return new Year();
    }

    /**
     * Create an instance of {@link U }
     * 
     */
    public U createU() {
        return new U();
    }

    /**
     * Create an instance of {@link ObjectList }
     * 
     */
    public ObjectList createObjectList() {
        return new ObjectList();
    }

    /**
     * Create an instance of {@link ReferenceList }
     * 
     */
    public ReferenceList createReferenceList() {
        return new ReferenceList();
    }

    /**
     * Create an instance of {@link ItemList }
     * 
     */
    public ItemList createItemList() {
        return new ItemList();
    }

    /**
     * Create an instance of {@link Item }
     * 
     */
    public Item createItem() {
        return new Item();
    }

    /**
     * Create an instance of {@link EndPage }
     * 
     */
    public EndPage createEndPage() {
        return new EndPage();
    }

    /**
     * Create an instance of {@link EndingDate }
     * 
     */
    public EndingDate createEndingDate() {
        return new EndingDate();
    }

    /**
     * Create an instance of {@link Day }
     * 
     */
    public Day createDay() {
        return new Day();
    }

    /**
     * Create an instance of {@link MmlMscarry }
     * 
     */
    public MmlMscarry createMmlMscarry() {
        return new MmlMscarry();
    }

    /**
     * Create an instance of {@link ArticleTitle }
     * 
     */
    public ArticleTitle createArticleTitle() {
        return new ArticleTitle();
    }

    /**
     * Create an instance of {@link DateRevised }
     * 
     */
    public DateRevised createDateRevised() {
        return new DateRevised();
    }

    /**
     * Create an instance of {@link SpaceFlightMission }
     * 
     */
    public SpaceFlightMission createSpaceFlightMission() {
        return new SpaceFlightMission();
    }

    /**
     * Create an instance of {@link MmlSep }
     * 
     */
    public MmlSep createMmlSep() {
        return new MmlSep();
    }

    /**
     * Create an instance of {@link MmlPiece }
     * 
     */
    public MmlPiece createMmlPiece() {
        return new MmlPiece();
    }

    /**
     * Create an instance of {@link MmlDegree }
     * 
     */
    public MmlDegree createMmlDegree() {
        return new MmlDegree();
    }

    /**
     * Create an instance of {@link MmlLogbase }
     * 
     */
    public MmlLogbase createMmlLogbase() {
        return new MmlLogbase();
    }

    /**
     * Create an instance of {@link Language }
     * 
     */
    public Language createLanguage() {
        return new Language();
    }

    /**
     * Create an instance of {@link MeshHeadingList }
     * 
     */
    public MeshHeadingList createMeshHeadingList() {
        return new MeshHeadingList();
    }

    /**
     * Create an instance of {@link MeshHeading }
     * 
     */
    public MeshHeading createMeshHeading() {
        return new MeshHeading();
    }

    /**
     * Create an instance of {@link Grant }
     * 
     */
    public Grant createGrant() {
        return new Grant();
    }

    /**
     * Create an instance of {@link OtherID }
     * 
     */
    public OtherID createOtherID() {
        return new OtherID();
    }

    /**
     * Create an instance of {@link DataBankList }
     * 
     */
    public DataBankList createDataBankList() {
        return new DataBankList();
    }

    /**
     * Create an instance of {@link DataBank }
     * 
     */
    public DataBank createDataBank() {
        return new DataBank();
    }

    /**
     * Create an instance of {@link Param }
     * 
     */
    public Param createParam() {
        return new Param();
    }

    /**
     * Create an instance of {@link Object }
     * 
     */
    public Object createObject() {
        return new Object();
    }

    /**
     * Create an instance of {@link MmlMlabeledtr }
     * 
     */
    public MmlMlabeledtr createMmlMlabeledtr() {
        return new MmlMlabeledtr();
    }

    /**
     * Create an instance of {@link MmlMtd }
     * 
     */
    public MmlMtd createMmlMtd() {
        return new MmlMtd();
    }

    /**
     * Create an instance of {@link MmlOtherwise }
     * 
     */
    public MmlOtherwise createMmlOtherwise() {
        return new MmlOtherwise();
    }

    /**
     * Create an instance of {@link GrantList }
     * 
     */
    public GrantList createGrantList() {
        return new GrantList();
    }

    /**
     * Create an instance of {@link MmlMprescripts }
     * 
     */
    public MmlMprescripts createMmlMprescripts() {
        return new MmlMprescripts();
    }

    /**
     * Create an instance of {@link MedlineJournalInfo }
     * 
     */
    public MedlineJournalInfo createMedlineJournalInfo() {
        return new MedlineJournalInfo();
    }

    /**
     * Create an instance of {@link BeginningDate }
     * 
     */
    public BeginningDate createBeginningDate() {
        return new BeginningDate();
    }

    /**
     * Create an instance of {@link CollectionTitle }
     * 
     */
    public CollectionTitle createCollectionTitle() {
        return new CollectionTitle();
    }

    /**
     * Create an instance of {@link CitationSubset }
     * 
     */
    public CitationSubset createCitationSubset() {
        return new CitationSubset();
    }

    /**
     * Create an instance of {@link GeneralNote }
     * 
     */
    public GeneralNote createGeneralNote() {
        return new GeneralNote();
    }

    /**
     * Create an instance of {@link JournalIssue }
     * 
     */
    public JournalIssue createJournalIssue() {
        return new JournalIssue();
    }

    /**
     * Create an instance of {@link PubDate }
     * 
     */
    public PubDate createPubDate() {
        return new PubDate();
    }

    /**
     * Create an instance of {@link BookDocumentSet }
     * 
     */
    public BookDocumentSet createBookDocumentSet() {
        return new BookDocumentSet();
    }

    /**
     * Create an instance of {@link DeleteDocument }
     * 
     */
    public DeleteDocument createDeleteDocument() {
        return new DeleteDocument();
    }

    /**
     * Create an instance of {@link Book }
     * 
     */
    public Book createBook() {
        return new Book();
    }

    /**
     * Create an instance of {@link BookTitle }
     * 
     */
    public BookTitle createBookTitle() {
        return new BookTitle();
    }

    /**
     * Create an instance of {@link AuthorList }
     * 
     */
    public AuthorList createAuthorList() {
        return new AuthorList();
    }

    /**
     * Create an instance of {@link InvestigatorList }
     * 
     */
    public InvestigatorList createInvestigatorList() {
        return new InvestigatorList();
    }

    /**
     * Create an instance of {@link Isbn }
     * 
     */
    public Isbn createIsbn() {
        return new Isbn();
    }

    /**
     * Create an instance of {@link ELocationID }
     * 
     */
    public ELocationID createELocationID() {
        return new ELocationID();
    }

    /**
     * Create an instance of {@link PubmedBookArticleSet }
     * 
     */
    public PubmedBookArticleSet createPubmedBookArticleSet() {
        return new PubmedBookArticleSet();
    }

    /**
     * Create an instance of {@link PublicationType }
     * 
     */
    public PublicationType createPublicationType() {
        return new PublicationType();
    }

    /**
     * Create an instance of {@link ISSN }
     * 
     */
    public ISSN createISSN() {
        return new ISSN();
    }

    /**
     * Create an instance of {@link Article }
     * 
     */
    public Article createArticle() {
        return new Article();
    }

    /**
     * Create an instance of {@link Journal }
     * 
     */
    public Journal createJournal() {
        return new Journal();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link Abstract }
     * 
     */
    public Abstract createAbstract() {
        return new Abstract();
    }

    /**
     * Create an instance of {@link PublicationTypeList }
     * 
     */
    public PublicationTypeList createPublicationTypeList() {
        return new PublicationTypeList();
    }

    /**
     * Create an instance of {@link ArticleDate }
     * 
     */
    public ArticleDate createArticleDate() {
        return new ArticleDate();
    }

    /**
     * Create an instance of {@link URL }
     * 
     */
    public URL createURL() {
        return new URL();
    }

    /**
     * Create an instance of {@link MmlAnnotationXml }
     * 
     */
    public MmlAnnotationXml createMmlAnnotationXml() {
        return new MmlAnnotationXml();
    }

    /**
     * Create an instance of {@link Investigator }
     * 
     */
    public Investigator createInvestigator() {
        return new Investigator();
    }

    /**
     * Create an instance of {@link OtherAbstract }
     * 
     */
    public OtherAbstract createOtherAbstract() {
        return new OtherAbstract();
    }

    /**
     * Create an instance of {@link Keyword }
     * 
     */
    public Keyword createKeyword() {
        return new Keyword();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link DateCompleted }
     * 
     */
    public DateCompleted createDateCompleted() {
        return new DateCompleted();
    }

    /**
     * Create an instance of {@link ChemicalList }
     * 
     */
    public ChemicalList createChemicalList() {
        return new ChemicalList();
    }

    /**
     * Create an instance of {@link SupplMeshList }
     * 
     */
    public SupplMeshList createSupplMeshList() {
        return new SupplMeshList();
    }

    /**
     * Create an instance of {@link KeywordList }
     * 
     */
    public KeywordList createKeywordList() {
        return new KeywordList();
    }

    /**
     * Create an instance of {@link StartPage }
     * 
     */
    public StartPage createStartPage() {
        return new StartPage();
    }

    /**
     * Create an instance of {@link ContractNumber }
     * 
     */
    public ContractNumber createContractNumber() {
        return new ContractNumber();
    }

    /**
     * Create an instance of {@link SupplMeshName }
     * 
     */
    public SupplMeshName createSupplMeshName() {
        return new SupplMeshName();
    }

    /**
     * Create an instance of {@link ContributionDate }
     * 
     */
    public ContributionDate createContributionDate() {
        return new ContributionDate();
    }

    /**
     * Create an instance of {@link DescriptorName }
     * 
     */
    public DescriptorName createDescriptorName() {
        return new DescriptorName();
    }

    /**
     * Create an instance of {@link DispFormula }
     * 
     */
    public DispFormula createDispFormula() {
        return new DispFormula();
    }

    /**
     * Create an instance of {@link MmlAnnotation }
     * 
     */
    public MmlAnnotation createMmlAnnotation() {
        return new MmlAnnotation();
    }

    /**
     * Create an instance of {@link MmlMtr }
     * 
     */
    public MmlMtr createMmlMtr() {
        return new MmlMtr();
    }

}
